blacklist=["goose_db_version", "postgres"]
schema="public"
[psql]
  dbname="yokoy-sync"
  host="localhost"
  port=5432
  user="dylan"
  pass=""
  sslmode="disable"

[[types]]
  [types.match]
    type = "types.Decimal"

  [types.replace]
    type = "decimal.Decimal"

  [types.imports]
    third_party = ['"github.com/shopspring/decimal"']
