// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("CompanyCards", testCompanyCards)
	t.Run("LegalEntities", testLegalEntities)
	t.Run("Trips", testTrips)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsDelete)
	t.Run("LegalEntities", testLegalEntitiesDelete)
	t.Run("Trips", testTripsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsQueryDeleteAll)
	t.Run("LegalEntities", testLegalEntitiesQueryDeleteAll)
	t.Run("Trips", testTripsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsSliceDeleteAll)
	t.Run("LegalEntities", testLegalEntitiesSliceDeleteAll)
	t.Run("Trips", testTripsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsExists)
	t.Run("LegalEntities", testLegalEntitiesExists)
	t.Run("Trips", testTripsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsFind)
	t.Run("LegalEntities", testLegalEntitiesFind)
	t.Run("Trips", testTripsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsBind)
	t.Run("LegalEntities", testLegalEntitiesBind)
	t.Run("Trips", testTripsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsOne)
	t.Run("LegalEntities", testLegalEntitiesOne)
	t.Run("Trips", testTripsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsAll)
	t.Run("LegalEntities", testLegalEntitiesAll)
	t.Run("Trips", testTripsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsCount)
	t.Run("LegalEntities", testLegalEntitiesCount)
	t.Run("Trips", testTripsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsHooks)
	t.Run("LegalEntities", testLegalEntitiesHooks)
	t.Run("Trips", testTripsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsInsert)
	t.Run("CompanyCards", testCompanyCardsInsertWhitelist)
	t.Run("LegalEntities", testLegalEntitiesInsert)
	t.Run("LegalEntities", testLegalEntitiesInsertWhitelist)
	t.Run("Trips", testTripsInsert)
	t.Run("Trips", testTripsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsReload)
	t.Run("LegalEntities", testLegalEntitiesReload)
	t.Run("Trips", testTripsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsReloadAll)
	t.Run("LegalEntities", testLegalEntitiesReloadAll)
	t.Run("Trips", testTripsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsSelect)
	t.Run("LegalEntities", testLegalEntitiesSelect)
	t.Run("Trips", testTripsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsUpdate)
	t.Run("LegalEntities", testLegalEntitiesUpdate)
	t.Run("Trips", testTripsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("CompanyCards", testCompanyCardsSliceUpdateAll)
	t.Run("LegalEntities", testLegalEntitiesSliceUpdateAll)
	t.Run("Trips", testTripsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
