// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Categories         string
	CompanyCards       string
	CostCenter         string
	ExpenseApproverIds string
	ExpenseCostCenter  string
	ExpenseEventLogs   string
	ExpenseTaxItems    string
	Expenses           string
	InvoiceCategories  string
	InvoiceLineItems   string
	InvoiceSuppliers   string
	Invoices           string
	LegalEntities      string
	Policies           string
	Tags               string
	TaxRates           string
	Trips              string
	Users              string
}{
	Categories:         "categories",
	CompanyCards:       "company_cards",
	CostCenter:         "cost_center",
	ExpenseApproverIds: "expense_approver_ids",
	ExpenseCostCenter:  "expense_cost_center",
	ExpenseEventLogs:   "expense_event_logs",
	ExpenseTaxItems:    "expense_tax_items",
	Expenses:           "expenses",
	InvoiceCategories:  "invoice_categories",
	InvoiceLineItems:   "invoice_line_items",
	InvoiceSuppliers:   "invoice_suppliers",
	Invoices:           "invoices",
	LegalEntities:      "legal_entities",
	Policies:           "policies",
	Tags:               "tags",
	TaxRates:           "tax_rates",
	Trips:              "trips",
	Users:              "users",
}
