// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCompanyCards(t *testing.T) {
	t.Parallel()

	query := CompanyCards()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCompanyCardsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCompanyCardsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CompanyCards().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCompanyCardsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CompanyCardSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCompanyCardsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CompanyCardExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if CompanyCard exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CompanyCardExists to return true, but got false.")
	}
}

func testCompanyCardsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	companyCardFound, err := FindCompanyCard(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if companyCardFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCompanyCardsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CompanyCards().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCompanyCardsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CompanyCards().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCompanyCardsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	companyCardOne := &CompanyCard{}
	companyCardTwo := &CompanyCard{}
	if err = randomize.Struct(seed, companyCardOne, companyCardDBTypes, false, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}
	if err = randomize.Struct(seed, companyCardTwo, companyCardDBTypes, false, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = companyCardOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = companyCardTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CompanyCards().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCompanyCardsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	companyCardOne := &CompanyCard{}
	companyCardTwo := &CompanyCard{}
	if err = randomize.Struct(seed, companyCardOne, companyCardDBTypes, false, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}
	if err = randomize.Struct(seed, companyCardTwo, companyCardDBTypes, false, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = companyCardOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = companyCardTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func companyCardBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func companyCardAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func companyCardAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func companyCardBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func companyCardAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func companyCardBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func companyCardAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func companyCardBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func companyCardAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CompanyCard) error {
	*o = CompanyCard{}
	return nil
}

func testCompanyCardsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &CompanyCard{}
	o := &CompanyCard{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, companyCardDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CompanyCard object: %s", err)
	}

	AddCompanyCardHook(boil.BeforeInsertHook, companyCardBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	companyCardBeforeInsertHooks = []CompanyCardHook{}

	AddCompanyCardHook(boil.AfterInsertHook, companyCardAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	companyCardAfterInsertHooks = []CompanyCardHook{}

	AddCompanyCardHook(boil.AfterSelectHook, companyCardAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	companyCardAfterSelectHooks = []CompanyCardHook{}

	AddCompanyCardHook(boil.BeforeUpdateHook, companyCardBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	companyCardBeforeUpdateHooks = []CompanyCardHook{}

	AddCompanyCardHook(boil.AfterUpdateHook, companyCardAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	companyCardAfterUpdateHooks = []CompanyCardHook{}

	AddCompanyCardHook(boil.BeforeDeleteHook, companyCardBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	companyCardBeforeDeleteHooks = []CompanyCardHook{}

	AddCompanyCardHook(boil.AfterDeleteHook, companyCardAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	companyCardAfterDeleteHooks = []CompanyCardHook{}

	AddCompanyCardHook(boil.BeforeUpsertHook, companyCardBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	companyCardBeforeUpsertHooks = []CompanyCardHook{}

	AddCompanyCardHook(boil.AfterUpsertHook, companyCardAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	companyCardAfterUpsertHooks = []CompanyCardHook{}
}

func testCompanyCardsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCompanyCardsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(companyCardColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCompanyCardsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCompanyCardsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CompanyCardSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCompanyCardsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CompanyCards().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	companyCardDBTypes = map[string]string{`ID`: `text`, `AccountReference`: `text`, `Currency`: `text`, `Description`: `text`, `Name`: `text`, `Number`: `text`, `OwnerID`: `text`, `StatusActive`: `boolean`, `LegalEntityID`: `text`}
	_                  = bytes.MinRead
)

func testCompanyCardsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(companyCardPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(companyCardAllColumns) == len(companyCardPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCompanyCardsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(companyCardAllColumns) == len(companyCardPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CompanyCard{}
	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, companyCardDBTypes, true, companyCardPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(companyCardAllColumns, companyCardPrimaryKeyColumns) {
		fields = companyCardAllColumns
	} else {
		fields = strmangle.SetComplement(
			companyCardAllColumns,
			companyCardPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CompanyCardSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCompanyCardsUpsert(t *testing.T) {
	t.Parallel()

	if len(companyCardAllColumns) == len(companyCardPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CompanyCard{}
	if err = randomize.Struct(seed, &o, companyCardDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CompanyCard: %s", err)
	}

	count, err := CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, companyCardDBTypes, false, companyCardPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CompanyCard struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CompanyCard: %s", err)
	}

	count, err = CompanyCards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
